### ISSUE TITLE
Coupled Head

### ISSUE THREAD

**Issue by www516717402** [fcjian/TOOD#1]
Thank you for share this great project.
Have you consider Decoupled head issue ?

**Comment by fcjian** [comment]
We consider that Decoupled head (i.e., Parallel head in the paper) might lead to a certain level of spatial misalignment in predictions between the two tasks, which was discussed in the paper.

**Comment by www516717402** [comment]
Great help. I will run this project in coco for comprehensive  more detail. Thank you.
