### ISSUE TITLE
Layer Attention instead of Channel Attention?

### ISSUE THREAD

**Issue by iumyx2612** [fcjian/TOOD#18]
Why did you choose Layer Attention instead of normal Channel Attention?  
Task-interactive features are concatenated after **N** consecutive Conv layers, then using Channel Attention could further separate each channels to specific task, instead of Layer Attention, which also conduct separation on channel dim, but can only separate in group of 6?

**Comment by fcjian** [comment]
The tasks of object classification and localization have different targets, and thus focus on different types of features (e.g. different levels or receptive fields). The N interactive layers in T-head have different effective receptive fields, which allow them to capture multiple levels of semantics. The layer attention is designed to make full use of this rich information by computing more meaningful features from those layers.

**Comment by iumyx2612** [comment]
> The tasks of object classification and localization have different targets, and thus focus on different types of features (e.g. different levels or receptive fields). The N interactive layers in T-head have different effective receptive fields, which allow them to capture multiple levels of semantics. The layer attention is designed to make full use of this rich information by computing more meaningful features from those layers.

I understand the intuition of Layer Attention. However, Layer Attention is just a special type of Channel Attention. And Channel Attention can also capture multi-level semantic features no? :thinking:

**Comment by iumyx2612** [comment]
@fcjian hello can we discuss about this when you have free time?

**Comment by fcjian** [comment]
@iumyx2612 The typical channel-wise attention is applied on a single layer. I hold the view that conducting channel-wise attention on multi-layers can be seen as the combination of the typical channel-wise attention and layer attention. So It can also capture multi-level semantic features but requires more parameters and FLOPs.

**Comment by iumyx2612** [comment]
> @iumyx2612 The typical channel-wise attention is applied on a single layer. We hold the view that conducting channel-wise attention on multi-layers can be seen as the combination of the typical channel-wise attention and layer attention. So It can also capture multi-level semantic features but requires more parameters and FLOPs.

Thank you very much, understood
